apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  namespace: blog
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
        name: blog
    spec:
      containers:
        - name: blog
          image: kimmingyu1/blog:latest
          ports:
            - containerPort: 3000
